//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adress
    {
        public int id { get; set; }
        public int idCity { get; set; }
        public string street { get; set; }
        public int house { get; set; }
        public int flat { get; set; }
        public int idPerson { get; set; }
    
        public virtual city city { get; set; }
        public virtual person person { get; set; }
    }
}
