//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public person()
        {
            this.adresses = new HashSet<adress>();
        }
    
        public int id { get; set; }
        public string firstName { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string telephone { get; set; }
    
        public virtual ICollection<adress> adresses { get; set; }
    }
}
